plugins {
    id 'net.fabricmc.fabric-loom-remap'
}

sourceSets {
    main {
        resources {
            srcDir project(":common").sourceSets.main.resources
        }
    }
}

loom {
    runs {
        clientGameTest {
            client()
            name "Client Game Test"
            vmArg "-Dfabric.client.gametest"
            runDir "run-gametest-${rootProject.minecraft_version}"
            source sourceSets.test
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
    mappings loom.officialMojangMappings()

    modImplementation "net.fabricmc:fabric-loader:${rootProject.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"

    modImplementation "dev.isxander:yet-another-config-lib:${rootProject.yacl_version}"
    modCompileOnly "com.terraformersmc:modmenu:${rootProject.modmenu_version}"
    if (!rootProject.minecraft_version.contains("-")) {
        modRuntimeOnly "com.terraformersmc:modmenu:${rootProject.modmenu_version}"
    }

    implementation project(path: ":common", configuration: "namedElements")
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    def mcVersion = rootProject.minecraft_version
    def expandMcVersion = mcVersion.contains('-') ? "${mcVersion.split('-')[0]}-" : mcVersion
    def mcDependency = rootProject.findProperty("minecraft_dependency") ?: ">=1.21 <=1.21.11"
    def expandProps = [
        "version": project.version,
        "loader_version": rootProject.loader_version,
        "minecraft_version": expandMcVersion,
        "minecraft_dependency": mcDependency
    ]
    inputs.properties expandProps

    filesMatching("fabric.mod.json") {
        expand expandProps
    }
}

tasks.named('jar', Jar).configure {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from project(":common").sourceSets.main.output
}

tasks.withType(Test).configureEach {
    failOnNoDiscoveredTests = false
}
