minecraft_version=26.1
minecraft_version_range=[26.1,26.2)
neoforge_version_range=[26.1,)
fabric_api_version=0.144.4+26.1
neoforge_version=26.1.2.109
yacl_version=3.9.6+26.1-fabric
yacl_neoforge_version=3.9.6+26.1-neoforge
modmenu_version=18.0.1
mod_version=0.4.0-26.1
