minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
neoforge_version_range=[26.2,)
fabric_api_version=0.158.0+26.2
neoforge_version=26.2.0.88
yacl_version=3.9.6+26.2-fabric
yacl_neoforge_version=3.9.6+26.2-neoforge
modmenu_version=20.0.1
mod_version=0.4.0-26.2
