plugins {
    id 'net.fabricmc.fabric-loom-remap'
}

loom {
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
    mappings loom.officialMojangMappings()

    modCompileOnly "net.fabricmc:fabric-loader:${rootProject.loader_version}"
    modImplementation "dev.isxander:yet-another-config-lib:${rootProject.yacl_version}"
}
