plugins {
    id 'net.neoforged.moddev'
}

neoForge {
    version = rootProject.neoforge_version
    validateAccessTransformers = false

    runs {
        client {
            client()
        }
    }

    mods {
        "hastemod" {
            sourceSet sourceSets.main
            sourceSet project(":common").sourceSets.main
        }
    }
}

dependencies {
    implementation("dev.isxander:yet-another-config-lib:${rootProject.yacl_neoforge_version}") {
        exclude group: 'thedarkcolour'
    }
    compileOnly project(":common")
}

tasks.named('jar', Jar).configure {
    from project(":common").sourceSets.main.output
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
